package main

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"strings"
)

const usageGenDBCluster = `kit gen db-cluster — emit docker-compose.yml for a Postgres primary + N replicas

Usage:
  kit gen db-cluster [--replicas N] [flags]

Defaults produce a master + 1 standby on localhost with streaming
replication, suitable for local dev of multi-replica routing code:

  $ kit gen db-cluster --out docker-compose.db.yml
  $ docker compose -f docker-compose.db.yml up -d
  $ DB_URL=postgres://app:changeme@localhost:5432/appdb \
    DB_READ_URLS=postgres://app:changeme@localhost:5433/appdb \
    ./your-service

The image (bitnamilegacy/postgresql:16 by default) carries env-driven
streaming-replication wiring, so no pg_basebackup or recovery.conf
script is needed — pinch from the [Bitnami PostgreSQL image docs]
(https://hub.docker.com/r/bitnamilegacy/postgresql) for variable
reference. The "bitnamilegacy" namespace is the community fallback
after Bitnami removed their free public images from the upstream
"bitnami/" namespace in late 2025.

Flags:
  --replicas        number of standby nodes (default 1, min 1)
  --image           docker image (default bitnamilegacy/postgresql:16)
  --db              application database name (default appdb)
  --user            application user (default app)
  --password        application password (default changeme; CHANGE for any persistent setup)
  --repl-user       replication-account user (default repl)
  --repl-password   replication-account password (default changeme)
  --primary-port    host port for the primary (default 5432)
  --port-base       host port for the FIRST replica (default 5433); subsequent replicas use port-base+1, +2, …
  --volume-prefix   docker named-volume prefix (default pgdata; final names: pgdata-primary, pgdata-standby-N)
  --out             output file (default: stdout)

Defaults are dev-friendly, not production-grade. For prod, mount real
secrets via docker secret / external secret store; never bake passwords
into committed compose files.
`

type dbClusterFlags struct {
	replicas     int
	image        string
	database     string
	username     string
	password     string
	replUser     string
	replPassword string
	primaryPort  int
	portBase     int
	volumePrefix string
	out          string
}

func runGenDBCluster(_ context.Context, args []string) error {
	fs := flag.NewFlagSet("gen db-cluster", flag.ContinueOnError)
	f := dbClusterFlags{}
	fs.IntVar(&f.replicas, "replicas", 1, "number of standby nodes (min 1)")
	fs.StringVar(&f.image, "image", "bitnamilegacy/postgresql:16", "docker image (must support POSTGRESQL_REPLICATION_MODE)")
	fs.StringVar(&f.database, "db", "appdb", "application database name")
	fs.StringVar(&f.username, "user", "app", "application user")
	fs.StringVar(&f.password, "password", "changeme", "application password")
	fs.StringVar(&f.replUser, "repl-user", "repl", "replication-account user")
	fs.StringVar(&f.replPassword, "repl-password", "changeme", "replication-account password")
	fs.IntVar(&f.primaryPort, "primary-port", 5432, "host port for the primary")
	fs.IntVar(&f.portBase, "port-base", 5433, "host port for the first replica; +N for subsequent")
	fs.StringVar(&f.volumePrefix, "volume-prefix", "pgdata", "named-volume prefix (final names pgdata-primary, pgdata-standby-N)")
	fs.StringVar(&f.out, "out", "", "output file (default: stdout)")
	fs.Usage = func() { fmt.Fprint(os.Stderr, usageGenDBCluster) }
	if err := fs.Parse(args); err != nil {
		return err
	}
	if f.replicas < 1 {
		f.replicas = 1
	}
	if f.image == "" {
		return errors.New("--image must not be empty")
	}
	if f.username == "" || f.password == "" || f.database == "" {
		return errors.New("--user, --password, --db must not be empty")
	}
	if f.replUser == "" || f.replPassword == "" {
		return errors.New("--repl-user, --repl-password must not be empty")
	}
	if f.primaryPort <= 0 || f.portBase <= 0 {
		return errors.New("--primary-port and --port-base must be positive")
	}
	w := io.Writer(os.Stdout)
	if f.out != "" {
		file, err := os.Create(f.out)
		if err != nil {
			return fmt.Errorf("create %s: %w", f.out, err)
		}
		defer file.Close()
		w = file
	}
	return emitDBClusterCompose(w, f)
}

// emitDBClusterCompose writes the docker-compose.yml body to w. The
// emitter is hand-rolled string assembly rather than yaml.Marshal so
// the output preserves a stable comment header + consistent indent
// that operators can review without a YAML diff tool.
func emitDBClusterCompose(w io.Writer, f dbClusterFlags) error {
	fmt.Fprintf(w, `# Generated by: kit gen db-cluster
#
# Postgres primary + %d standby with streaming replication.
# Use for LOCAL DEV — change passwords + mount real secrets for prod.
#
# Bring up:
#   docker compose -f <this-file> up -d
#
# Hostnames (within the compose network): primary, standby-1, standby-2, …
# Host ports: primary=%d, standby-1=%d, standby-2=%d, …
#
# Application env:
#   DB_URL=postgres://%s:%s@localhost:%d/%s
#   DB_READ_URLS=%s

services:
`, f.replicas, f.primaryPort, f.portBase, f.portBase+1,
		f.username, f.password, f.primaryPort, f.database,
		buildReadURLsExample(f))

	emitPrimaryService(w, f)
	for i := 1; i <= f.replicas; i++ {
		emitReplicaService(w, f, i)
	}

	// Networks + volumes blocks.
	fmt.Fprintf(w, `
networks:
  default:
    name: %s-net

volumes:
  %s-primary:
`, f.volumePrefix, f.volumePrefix)
	for i := 1; i <= f.replicas; i++ {
		fmt.Fprintf(w, "  %s-standby-%d:\n", f.volumePrefix, i)
	}
	return nil
}

// emitPrimaryService writes the primary service block.
func emitPrimaryService(w io.Writer, f dbClusterFlags) {
	fmt.Fprintf(w, `  primary:
    image: %s
    container_name: %s-primary
    environment:
      POSTGRESQL_REPLICATION_MODE: master
      POSTGRESQL_REPLICATION_USER: %s
      POSTGRESQL_REPLICATION_PASSWORD: %s
      POSTGRESQL_USERNAME: %s
      POSTGRESQL_PASSWORD: %s
      POSTGRESQL_POSTGRES_PASSWORD: %s
      POSTGRESQL_DATABASE: %s
    ports:
      - "%d:5432"
    volumes:
      - %s-primary:/bitnami/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "%s", "-d", "%s"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 30s
`, f.image, f.volumePrefix,
		f.replUser, f.replPassword,
		f.username, f.password, f.password,
		f.database,
		f.primaryPort,
		f.volumePrefix,
		f.username, f.database)
}

// emitReplicaService writes a single standby service block, numbered
// with `index` (1-based, matching the standby-1 / standby-2 alias).
func emitReplicaService(w io.Writer, f dbClusterFlags, index int) {
	hostPort := f.portBase + (index - 1)
	fmt.Fprintf(w, `
  standby-%d:
    image: %s
    container_name: %s-standby-%d
    depends_on:
      primary:
        condition: service_healthy
    environment:
      POSTGRESQL_REPLICATION_MODE: slave
      POSTGRESQL_REPLICATION_USER: %s
      POSTGRESQL_REPLICATION_PASSWORD: %s
      POSTGRESQL_USERNAME: %s
      POSTGRESQL_PASSWORD: %s
      POSTGRESQL_POSTGRES_PASSWORD: %s
      POSTGRESQL_DATABASE: %s
      POSTGRESQL_MASTER_HOST: primary
      POSTGRESQL_MASTER_PORT_NUMBER: "5432"
    ports:
      - "%d:5432"
    volumes:
      - %s-standby-%d:/bitnami/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "%s", "-d", "%s"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 30s
`, index, f.image, f.volumePrefix, index,
		f.replUser, f.replPassword,
		f.username, f.password, f.password,
		f.database,
		hostPort,
		f.volumePrefix, index,
		f.username, f.database)
}

// buildReadURLsExample renders a comma-separated DB_READ_URLS value
// so operators can copy-paste it directly. Used only in the header
// comment, not in the YAML body.
func buildReadURLsExample(f dbClusterFlags) string {
	parts := make([]string, 0, f.replicas)
	for i := 0; i < f.replicas; i++ {
		parts = append(parts, fmt.Sprintf("postgres://%s:%s@localhost:%d/%s",
			f.username, f.password, f.portBase+i, f.database))
	}
	return strings.Join(parts, ",")
}
