package main

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"
)

const usageGenMigration = `kit gen migration — scaffold a timestamped pair of SQL files

Usage:
  kit gen migration <name> [--dir migrations]

Example:
  kit gen migration add_user_index
    → migrations/20260601120000_add_user_index.up.sql
    → migrations/20260601120000_add_user_index.down.sql

Files contain a header comment with the timestamp and name; both
SQL bodies are empty. Idempotent — refuses to clobber existing
files with the same timestamp + name.

Name must match [a-z0-9_]+ — lowercase, underscores; no dashes or
spaces so the resulting prefix collates lexically and parses
cleanly by the migration runner.
`

var migrationNameRE = regexp.MustCompile(`^[a-z0-9_]+$`)

func runGenMigration(_ context.Context, args []string) error {
	fs := flag.NewFlagSet("gen migration", flag.ContinueOnError)
	dir := fs.String("dir", "migrations", "directory for migration files")
	fs.Usage = func() { fmt.Fprint(os.Stderr, usageGenMigration) }
	if err := fs.Parse(args); err != nil {
		return err
	}
	if fs.NArg() < 1 {
		fs.Usage()
		return errors.New("migration name is required")
	}
	name := strings.TrimSpace(fs.Arg(0))
	if !migrationNameRE.MatchString(name) {
		return fmt.Errorf("name %q does not match [a-z0-9_]+", name)
	}
	if err := os.MkdirAll(*dir, 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", *dir, err)
	}
	ts := time.Now().UTC().Format("20060102150405")
	base := ts + "_" + name
	up := filepath.Join(*dir, base+".up.sql")
	down := filepath.Join(*dir, base+".down.sql")
	if exists(up) || exists(down) {
		return fmt.Errorf("refusing to clobber existing %s / %s", up, down)
	}
	if err := writeMigrationFile(up, name, ts, false); err != nil {
		return err
	}
	if err := writeMigrationFile(down, name, ts, true); err != nil {
		return err
	}
	fmt.Printf("kit gen migration:\n  %s\n  %s\n", up, down)
	fmt.Println("\nEdit the SQL bodies, then `kit migrate up`.")
	return nil
}

func exists(p string) bool {
	_, err := os.Stat(p)
	return err == nil
}

func writeMigrationFile(path, name, ts string, isDown bool) error {
	kind := "Up"
	hint := "Apply schema changes."
	if isDown {
		kind = "Down"
		hint = "Roll back the matching Up."
	}
	body := fmt.Sprintf(`-- %s migration: %s
-- Generated by kit gen migration at %s UTC
-- %s

`, kind, name, ts, hint)
	return os.WriteFile(path, []byte(body), 0o644)
}
